name: Build Docker Image with Custom DNS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build Docker container with custom DNS
        run: |
          docker buildx build --build-arg DNS_SERVER=8.8.8.8 -t my-container-image -f Dockerfile .

