name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Create a Docker network with custom DNS
        run: docker network create --driver bridge custom_network

      - name: Build Docker container
        run: docker buildx build --network custom_network -t my-container-image -f Dockerfile .

      - name: Remove Docker network
        run: docker network rm custom_network

